# 应用服务 WEB 访问端口
server.port=${BACKEND_PORT:8080}

#mysql数据库连接
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/zzyl?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:we005218}


#mybatisplus
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath:/mapper/*.xml


#配置阿里云oss服务的访问信息
aliyun.oss.endpoint=${ALIYUN_OSS_ENDPOINT:https://oss-cn-chengdu.aliyuncs.com}
aliyun.oss.bucketName=${ALIYUN_OSS_BUCKET:zzyl-706}
aliyun.oss.region=${ALIYUN_OSS_REGION:cn-chengdu}


